// =============================================================================
// Baustein:      DB2 "Positionen"
// Functionality: Speicher für die Soll-Positionen der X-Achse
// =============================================================================
// Change log table:
// | Version | Date       |  Expert              |   Changes applied
// -----------------------------------------------------------------------------
// | 01.00.00| 05.12.2025 |  Boris Quade (66528) |   Erste Version
// =============================================================================
DATA_BLOCK DB2
TITLE = 'Positionen'
VERSION : '1.0'

    STRUCT
        Pos1 : INT := 100; // Ablageposition Kunststoff / Metall ohne Bohrung
        Pos2 : INT := 75;  // Ablageposition Metall mit Bohrung
        Pos3 : INT := 50;  // Reserve
        Pos4 : INT := 25;  // Reserve
    END_STRUCT

BEGIN
END_DATA_BLOCK